"""Runtime configuration for the ESP32 CSI visualizer."""

POLL_INTERVAL = 0.1
SCAN_INTERVAL = 10

MOTION_THRESHOLD_STD = 0.3
MOTION_THRESHOLD_COMPOSITE = 1.2

SCENE_BASELINE_FRAMES = 80
SCENE_BASELINE_TIMEOUT = 30
SCENE_SMOOTHING_WINDOW = 4
SCENE_AVERAGE_WINDOW = 12
SCENE_CONTOUR_SIGMA = 2.2
SCENE_CONTOUR_FLOOR = 0.04

CSI_LOW_AMPLITUDE_THRESHOLD = 0.03
CSI_LOW_AMPLITUDE_STREAK = 8
